### PR TITLE
Bumped version

### PR DESCRIPTION
**Pull request by JensErat**

### CODE REVIEW

**Comment by ypid** [comment]
I wanted to test version 4.1.1 for a few days before opening the PR but you where quicker :smile: I have no complinces with 4.1.1.

**Comment by JensErat** [comment]
In the end, it was only a minor update, and the version number just changes what's downloaded as a minor convenience helper...

After getting familiar with Seafile for a while, I decided to update the image at some time in future and run the database update scripts as needed, so upgrading seafile is more convenient (and at the same time, I will apply some larger cleanups to the Dockerfile, which does not really conform to the Docker best practices. But it will take some more time, I have to think a little bit about those changes so I don't break anything.

**Comment by ypid** [comment]
Good idea. I had also something like this in mind. Do you intent to include Seafile in the image itself to make it easier to update to a new Seafile version and run multpile Seafile instances?

**Comment by JensErat** [comment]
Yes, and maybe splitting up into multiple images (seafile, seahub) which can be joined again. But I didn't dig too deep into this up to now, but something must and will be done. ;) And it seems there is demand for proper Seafile images looking at the Docker and GitHub stats.

The thing that bugs be most is the database upgrade, I'm unsure how robust this is; if I don't get enough confidence by reading the code I'll query for feedback on the Seafile mailing list.

**Pull request merged**
